/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.warehousemanagementsystem;

import DBwarehouse.DBconnector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ama
 */
public class AddNewStorageJob extends javax.swing.JFrame {

    /**
     * Creates new form AddNewStorageJob
     */
    public AddNewStorageJob() {
        initComponents();
        
        Update_Client();
        Updated_Storage_Jobs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtClientD = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btnAddNewStorageBacktoMngMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableStorageJobINfo = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtCompanyName = new javax.swing.JTextField();
        txtClientName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cmbSlot = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableClientSelect = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        cmbDuration = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        dataStartDate = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ADD NEW STORAGE JOB");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Warehouse Management System");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(567, 567, 567)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Client Name");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Company Name");

        txtClientD.setBackground(new java.awt.Color(255, 255, 255));
        txtClientD.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtClientD.setForeground(new java.awt.Color(0, 0, 0));
        txtClientD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClientDActionPerformed(evt);
            }
        });

        btnsave.setBackground(new java.awt.Color(0, 153, 153));
        btnsave.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnsave.setForeground(new java.awt.Color(0, 0, 0));
        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnAddNewStorageBacktoMngMenu.setBackground(new java.awt.Color(0, 153, 153));
        btnAddNewStorageBacktoMngMenu.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnAddNewStorageBacktoMngMenu.setForeground(new java.awt.Color(0, 0, 0));
        btnAddNewStorageBacktoMngMenu.setText("BACK");
        btnAddNewStorageBacktoMngMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewStorageBacktoMngMenuActionPerformed(evt);
            }
        });

        tableStorageJobINfo.setBackground(new java.awt.Color(255, 255, 255));
        tableStorageJobINfo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tableStorageJobINfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.J.ID", "Client ID", "Client name", "Slot given", "Start date", "Duration"
            }
        ));
        tableStorageJobINfo.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableStorageJobINfo.setRowHeight(25);
        tableStorageJobINfo.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tableStorageJobINfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableStorageJobINfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableStorageJobINfo);
        if (tableStorageJobINfo.getColumnModel().getColumnCount() > 0) {
            tableStorageJobINfo.getColumnModel().getColumn(0).setMinWidth(38);
            tableStorageJobINfo.getColumnModel().getColumn(0).setMaxWidth(38);
            tableStorageJobINfo.getColumnModel().getColumn(3).setMinWidth(60);
            tableStorageJobINfo.getColumnModel().getColumn(3).setMaxWidth(60);
            tableStorageJobINfo.getColumnModel().getColumn(5).setMinWidth(55);
            tableStorageJobINfo.getColumnModel().getColumn(5).setMaxWidth(55);
        }

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Storage Job Information");

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        txtCompanyName.setBackground(new java.awt.Color(255, 255, 255));
        txtCompanyName.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtCompanyName.setForeground(new java.awt.Color(0, 0, 0));
        txtCompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompanyNameActionPerformed(evt);
            }
        });

        txtClientName.setBackground(new java.awt.Color(255, 255, 255));
        txtClientName.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtClientName.setForeground(new java.awt.Color(0, 0, 0));
        txtClientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClientNameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Client ID");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Duration (weeks)");

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Slot Given");

        cmbSlot.setBackground(new java.awt.Color(102, 102, 102));
        cmbSlot.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        cmbSlot.setForeground(new java.awt.Color(0, 0, 0));
        cmbSlot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9" }));

        TableClientSelect.setBackground(new java.awt.Color(255, 255, 255));
        TableClientSelect.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        TableClientSelect.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Client ID", "Client name", "NIC", "Company name", "Address", "Phone number", "Category"
            }
        ));
        TableClientSelect.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TableClientSelect.setRowHeight(25);
        TableClientSelect.setSelectionBackground(new java.awt.Color(0, 153, 153));
        TableClientSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableClientSelectMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableClientSelect);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Select The Client");

        cmbDuration.setBackground(new java.awt.Color(102, 102, 102));
        cmbDuration.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        cmbDuration.setForeground(new java.awt.Color(0, 0, 0));
        cmbDuration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Category");

        txtCategory.setBackground(new java.awt.Color(255, 255, 255));
        txtCategory.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtCategory.setForeground(new java.awt.Color(0, 0, 0));
        txtCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoryActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Start date");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbDuration, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbSlot, 0, 151, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCompanyName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtClientName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtClientD, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCategory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(dataStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddNewStorageBacktoMngMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(505, 505, 505))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClientD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(dataStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cmbDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbSlot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsave)
                    .addComponent(btnAddNewStorageBacktoMngMenu))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtClientDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClientDActionPerformed

    private void txtCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompanyNameActionPerformed

    private void txtClientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClientNameActionPerformed

    private void btnAddNewStorageBacktoMngMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewStorageBacktoMngMenuActionPerformed
        // TODO add your handling code here:
        
        ManagerMenu mngr = new ManagerMenu();
        mngr.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnAddNewStorageBacktoMngMenuActionPerformed

    private void txtCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoryActionPerformed

    private void TableClientSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableClientSelectMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel def4 = (DefaultTableModel)TableClientSelect.getModel();
        
        int selectIndex = TableClientSelect.getSelectedRow();
        
        txtClientD.setText(def4.getValueAt(selectIndex, 0).toString());
        txtClientName.setText(def4.getValueAt(selectIndex, 1).toString());
        txtCompanyName.setText(def4.getValueAt(selectIndex, 3).toString());
        txtCategory.setText(def4.getValueAt(selectIndex, 6).toString());        
    }//GEN-LAST:event_TableClientSelectMouseClicked

    
    
    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        
        String ClientID = txtClientD.getText();
        String ClientName = txtClientName.getText();
        String CompanyName = txtCompanyName.getText();
        String Category = txtCategory.getText();
        
        SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        String StartDate = dateformat.format(dataStartDate.getDate());
      
        String Duration = cmbDuration.getSelectedItem().toString();
        String SlotGiven = cmbSlot.getSelectedItem().toString();
        //String StorageJobID = txtSJID.getText();
        
        if(ClientID.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Insert The Client ID");
        }
        
        else if(ClientName.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Insert The Client Name");
        }
        
        else if(CompanyName.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Insert The Company Name");
        }
        
        else if(Category.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Insert The Category");
        }
        
        else if(StartDate.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Insert The Start Date");
        }
        
        else if(Duration.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Select The Duration");
        }
        
        else if(SlotGiven.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Select The Slot");
        }
        else {
            
            
        try {
            
            
            
            PreparedStatement stmt1;
            String query = "INSERT INTO `addedstoragejobs`( `Client_ID`, `Client_Name`, `Slot_Given`, `Start_Date`, `Duration`) VALUES (?,?,?,?,?)";
           
            
            stmt1 = DBconnector.getConnection().prepareStatement(query);
            
            stmt1.setString(1, ClientID);
            stmt1.setString(2, ClientName);
            stmt1.setString(3, SlotGiven);
            stmt1.setString(4, StartDate);
            stmt1.setString(5, Duration);
            
            if(stmt1.executeUpdate() > 0)
            {
                JOptionPane.showMessageDialog(null,"ADDED");
            }
            
        txtClientD.setText("");
        txtClientName.setText("");
        dataStartDate.setCalendar(null);
        txtClientD.requestFocus();
        
      Updated_Storage_Jobs();  
            
        }
        
        catch (SQLException ex) {
            Logger.getLogger(RegisterClients.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
        
    }//GEN-LAST:event_btnsaveActionPerformed

    private void tableStorageJobINfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableStorageJobINfoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tableStorageJobINfoMouseClicked

    public void Update_Client()
    {
        int log;
        
         try {
            DBconnector db = new DBconnector();
            Connection con = db.getConnection();
           
            PreparedStatement pre1 = null;
            pre1 = con.prepareStatement("SELECT * FROM `clientsregistration`");
            ResultSet R_set  = pre1.executeQuery();
            
            ResultSetMetaData result = R_set.getMetaData();
            log = result.getColumnCount();
            DefaultTableModel Deftbl = (DefaultTableModel)TableClientSelect.getModel();
            Deftbl.setRowCount(0);
            
            while(R_set.next())
            {
                Vector table = new Vector();
                for (int i=1; i<=log; i++)
                {
                  
                   table.add(R_set.getString("Client_ID"));
                   table.add(R_set.getString("Client_Name"));
                   table.add(R_set.getString("NIC"));
                   table.add(R_set.getString("Company_Name"));
                   table.add(R_set.getString("Address"));
                   table.add(R_set.getString("Phone_Number"));
                   table.add(R_set.getString("Category"));
                   
                }
                
                Deftbl.addRow(table);
                
            }
          
            
        } catch (SQLException ex) {
            Logger.getLogger(CreateOperatorAccounts.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void Updated_Storage_Jobs()
    {
        int log;
        
         try {
            DBconnector db = new DBconnector();
            Connection con = db.getConnection();
           
            PreparedStatement pre1 = null;
            pre1 = con.prepareStatement("SELECT * FROM `addedstoragejobs`");
            ResultSet R_set  = pre1.executeQuery();
            
            ResultSetMetaData result = R_set.getMetaData();
            log = result.getColumnCount();
            DefaultTableModel Deftbl = (DefaultTableModel)tableStorageJobINfo.getModel();
            Deftbl.setRowCount(0);
            
            while(R_set.next())
            {
                Vector table = new Vector();
                for (int i=1; i<=log; i++)
                {
                  
                   table.add(R_set.getString("Storage_Job_ID"));
                   table.add(R_set.getString("Client_ID"));
                   table.add(R_set.getString("Client_Name"));
                   table.add(R_set.getString("Slot_Given"));
                   table.add(R_set.getString("Start_Date"));
                   table.add(R_set.getString("Duration"));
                   
                }
                
                Deftbl.addRow(table);
                
            }
          
            
        } catch (SQLException ex) {
            Logger.getLogger(CreateOperatorAccounts.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewStorageJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewStorageJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewStorageJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewStorageJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewStorageJob().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableClientSelect;
    private javax.swing.JButton btnAddNewStorageBacktoMngMenu;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> cmbDuration;
    private javax.swing.JComboBox<String> cmbSlot;
    private com.toedter.calendar.JDateChooser dataStartDate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableStorageJobINfo;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtClientD;
    private javax.swing.JTextField txtClientName;
    private javax.swing.JTextField txtCompanyName;
    // End of variables declaration//GEN-END:variables
}
