/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.warehousemanagementsystem;

import DBwarehouse.DBconnector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ama
 */
public class CalculateTheBillForStorageJob extends javax.swing.JFrame {

    /**
     * Creates new form CalculateTheBillForStorageJob
     */
    public CalculateTheBillForStorageJob() {
        initComponents();
        
        Updated_Storage_Jobs();
        update_bill();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tableStorageJobINfo2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BTNCALCBILL = new javax.swing.JButton();
        btnCalcBillBacktoMngMenu = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnsavefinal = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtSJID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableStorageJobINfo = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableStorageJobINfo1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableStorageJobINfo3 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtCID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtSID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtduration = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtBillamnt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtpayed = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtbalance = new javax.swing.JTextField();
        BTNCALCBLANCE = new javax.swing.JButton();

        tableStorageJobINfo2.setBackground(new java.awt.Color(255, 255, 255));
        tableStorageJobINfo2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tableStorageJobINfo2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.J.ID", "Client ID", "Client name", "Slot given", "Start date", "Duration"
            }
        ));
        tableStorageJobINfo2.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableStorageJobINfo2.setRowHeight(25);
        tableStorageJobINfo2.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tableStorageJobINfo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableStorageJobINfo2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableStorageJobINfo2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CLACULATE THE BILL FOR STORAGE JOBS");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Warehouse Management System");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(453, 453, 453)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BTNCALCBILL.setBackground(new java.awt.Color(0, 153, 153));
        BTNCALCBILL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        BTNCALCBILL.setForeground(new java.awt.Color(0, 0, 0));
        BTNCALCBILL.setText("CALCULATE BILL");
        BTNCALCBILL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCALCBILLActionPerformed(evt);
            }
        });

        btnCalcBillBacktoMngMenu.setBackground(new java.awt.Color(0, 153, 153));
        btnCalcBillBacktoMngMenu.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnCalcBillBacktoMngMenu.setForeground(new java.awt.Color(0, 0, 0));
        btnCalcBillBacktoMngMenu.setText("BACK");
        btnCalcBillBacktoMngMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcBillBacktoMngMenuActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("CLEAR ALL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Select the Slot Price ( Package )");

        btnsavefinal.setBackground(new java.awt.Color(0, 153, 153));
        btnsavefinal.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnsavefinal.setForeground(new java.awt.Color(0, 0, 0));
        btnsavefinal.setText("Save");
        btnsavefinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsavefinalActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Storage job ID");

        txtSJID.setBackground(new java.awt.Color(255, 255, 255));
        txtSJID.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtSJID.setForeground(new java.awt.Color(0, 0, 0));
        txtSJID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSJIDActionPerformed(evt);
            }
        });

        tableStorageJobINfo.setBackground(new java.awt.Color(255, 255, 255));
        tableStorageJobINfo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tableStorageJobINfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"A1", "10 000.00"},
                {"A2", "10 000.00"},
                {"A3", "10 000.00"},
                {"A4", "10 000.00"},
                {"A5", "10 000.00"},
                {"A6", "10 000.00"},
                {"A7", "10 000.00"},
                {"A8", "10 000.00"},
                {"A9", "10 000.00"},
                {"B1", "20 000.00"},
                {"B2", "20 000.00"},
                {"B3", "20 000.00"},
                {"B4", "20 000.00"},
                {"B5", "20 000.00"},
                {"B6", "20 000.00"},
                {"B7", "20 000.00"},
                {"B8", "20 000.00"},
                {"B9", "20 000.00"}
            },
            new String [] {
                "Slot", "Price"
            }
        ));
        tableStorageJobINfo.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableStorageJobINfo.setRowHeight(25);
        tableStorageJobINfo.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tableStorageJobINfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableStorageJobINfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableStorageJobINfo);

        tableStorageJobINfo1.setBackground(new java.awt.Color(255, 255, 255));
        tableStorageJobINfo1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tableStorageJobINfo1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.J.ID", "Client ID", "Client name", "Slot given", "Start date", "Duration"
            }
        ));
        tableStorageJobINfo1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableStorageJobINfo1.setRowHeight(25);
        tableStorageJobINfo1.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tableStorageJobINfo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableStorageJobINfo1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableStorageJobINfo1);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Select Storage Job Information");

        tableStorageJobINfo3.setBackground(new java.awt.Color(255, 255, 255));
        tableStorageJobINfo3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tableStorageJobINfo3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill Number", "Client ID", "Duration", "Slot", "Bill Amount"
            }
        ));
        tableStorageJobINfo3.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableStorageJobINfo3.setRowHeight(25);
        tableStorageJobINfo3.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tableStorageJobINfo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableStorageJobINfo3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableStorageJobINfo3);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Bill Summary");

        txtCID.setBackground(new java.awt.Color(255, 255, 255));
        txtCID.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtCID.setForeground(new java.awt.Color(0, 0, 0));
        txtCID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCIDActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Client ID");

        txtCName.setBackground(new java.awt.Color(255, 255, 255));
        txtCName.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtCName.setForeground(new java.awt.Color(0, 0, 0));
        txtCName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCNameActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Client Name");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Slot Given");

        txtSID.setBackground(new java.awt.Color(255, 255, 255));
        txtSID.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtSID.setForeground(new java.awt.Color(0, 0, 0));
        txtSID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSIDActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Duration");

        txtPrice.setBackground(new java.awt.Color(255, 255, 255));
        txtPrice.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(0, 0, 0));
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Price for the Slot");

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Duration ( Weeks )");

        txtduration.setBackground(new java.awt.Color(255, 255, 255));
        txtduration.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtduration.setForeground(new java.awt.Color(0, 0, 0));
        txtduration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdurationActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Bill Amount");

        txtBillamnt.setBackground(new java.awt.Color(255, 255, 255));
        txtBillamnt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtBillamnt.setForeground(new java.awt.Color(0, 0, 0));
        txtBillamnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBillamntActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Payed Amount");

        txtpayed.setBackground(new java.awt.Color(255, 255, 255));
        txtpayed.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtpayed.setForeground(new java.awt.Color(0, 0, 0));
        txtpayed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpayedActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Balance");

        txtbalance.setBackground(new java.awt.Color(255, 255, 255));
        txtbalance.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtbalance.setForeground(new java.awt.Color(0, 0, 0));
        txtbalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbalanceActionPerformed(evt);
            }
        });

        BTNCALCBLANCE.setBackground(new java.awt.Color(0, 153, 153));
        BTNCALCBLANCE.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        BTNCALCBLANCE.setForeground(new java.awt.Color(0, 0, 0));
        BTNCALCBLANCE.setText("CALCULATE BALACE");
        BTNCALCBLANCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCALCBLANCEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCID)
                                    .addComponent(txtCName)
                                    .addComponent(txtSID)
                                    .addComponent(txtSJID, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtduration, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtpayed, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBillamnt, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addComponent(BTNCALCBLANCE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(jLabel5)))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnCalcBillBacktoMngMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(201, 201, 201)
                                .addComponent(BTNCALCBILL)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(txtbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnsavefinal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel9)
                                                .addGap(42, 42, 42)
                                                .addComponent(jLabel14))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(61, 61, 61)
                                                .addComponent(txtCName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txtSJID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(36, 36, 36)
                                                .addComponent(txtSID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(337, 337, 337)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txtduration, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel17)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BTNCALCBLANCE)
                                                .addGap(11, 11, 11)))))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnCalcBillBacktoMngMenu)
                                    .addComponent(jButton3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(299, 299, 299)
                                        .addComponent(jLabel13))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtBillamnt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtpayed, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)
                                    .addComponent(btnsavefinal)
                                    .addComponent(BTNCALCBILL))
                                .addGap(27, 27, 27))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableStorageJobINfo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableStorageJobINfo2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableStorageJobINfo2MouseClicked

    private void txtSIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSIDActionPerformed

    private void txtCNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCNameActionPerformed

    private void txtCIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCIDActionPerformed

    private void tableStorageJobINfo3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableStorageJobINfo3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableStorageJobINfo3MouseClicked

    private void tableStorageJobINfo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableStorageJobINfo1MouseClicked
        // TODO add your handling code here:
        
         DefaultTableModel def6 = (DefaultTableModel)tableStorageJobINfo1.getModel();
        
        int selectIndex = tableStorageJobINfo1.getSelectedRow();
        
        txtSJID.setText(def6.getValueAt(selectIndex, 0).toString());
        txtCID.setText(def6.getValueAt(selectIndex, 1).toString());
        txtCName.setText(def6.getValueAt(selectIndex, 2).toString());
        txtSID.setText(def6.getValueAt(selectIndex, 3).toString());   
        txtduration.setText(def6.getValueAt(selectIndex, 5).toString()); 
        
    }//GEN-LAST:event_tableStorageJobINfo1MouseClicked

    private void tableStorageJobINfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableStorageJobINfoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableStorageJobINfoMouseClicked

    private void txtSJIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSJIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSJIDActionPerformed

    private void btnCalcBillBacktoMngMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcBillBacktoMngMenuActionPerformed
        // TODO add your handling code here:

        ManagerMenu mngr = new ManagerMenu();
        mngr.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnCalcBillBacktoMngMenuActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void txtdurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdurationActionPerformed

    private void txtBillamntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBillamntActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_txtBillamntActionPerformed

    private void txtpayedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpayedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpayedActionPerformed

    private void txtbalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbalanceActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        txtSJID.setText("");
        txtCID.setText("");
        txtCName.setText("");
        txtSID.setText("");
        txtPrice.setText("");
        txtduration.setText("");
        txtBillamnt.setText("");
        txtpayed.setText("");
        txtbalance.setText("");
        txtSJID.requestFocus();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BTNCALCBILLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCALCBILLActionPerformed
        // TODO add your handling code here:
        
    
        int days = Integer.parseInt(txtduration.getText());
        int price = Integer.parseInt(txtPrice.getText());
        
        int tot = days * price;
        
        txtBillamnt.setText(String.valueOf(tot));
    
        
    }//GEN-LAST:event_BTNCALCBILLActionPerformed

    private void BTNCALCBLANCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCALCBLANCEActionPerformed
        // TODO add your handling code here:
        
        int bill = Integer.parseInt(txtBillamnt.getText());
        int payed = Integer.parseInt(txtpayed.getText());
        
        int bal = payed - bill;
        
        txtbalance.setText(String.valueOf(bal));
        
    }//GEN-LAST:event_BTNCALCBLANCEActionPerformed

    private void btnsavefinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsavefinalActionPerformed
        // TODO add your handling code here:
        
        String Clientid = txtCID.getText();
        String duration = txtduration.getText();
        String slot = txtSID.getText();
        String billamnt = txtBillamnt.getText();
        
        
        try {
            
            
            
            PreparedStatement stmt1;
            String query = "INSERT INTO `billtable`( `Client_id`, `Duration`, `Slot`, `Bill_Amount`) VALUES (?,?,?,?)";
           
            
            stmt1 = DBconnector.getConnection().prepareStatement(query);
            
            stmt1.setString(1, Clientid);
            stmt1.setString(2, duration);
            stmt1.setString(3, slot);
            stmt1.setString(4, billamnt);
            
            if(stmt1.executeUpdate() > 0)
            {
                JOptionPane.showMessageDialog(null,"User Added");
            }
            
        txtCID.setText("");
        txtduration.setText("");
        txtSID.setText("");
        txtBillamnt.requestFocus();
        
            update_bill();
        }
        
        catch (SQLException ex) {
            Logger.getLogger(CalculateTheBillForStorageJob.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_btnsavefinalActionPerformed

    public void Updated_Storage_Jobs()
    {
        int log;
        
         try {
            DBconnector db = new DBconnector();
            Connection con = db.getConnection();
           
            PreparedStatement pre1 = null;
            pre1 = con.prepareStatement("SELECT * FROM `addedstoragejobs`");
            ResultSet R_set  = pre1.executeQuery();
            
            ResultSetMetaData result = R_set.getMetaData();
            log = result.getColumnCount();
            DefaultTableModel Deftbl = (DefaultTableModel)tableStorageJobINfo1.getModel();
            Deftbl.setRowCount(0);
            
            while(R_set.next())
            {
                Vector table = new Vector();
                for (int i=1; i<=log; i++)
                {
                  
                   table.add(R_set.getString("Storage_Job_ID"));
                   table.add(R_set.getString("Client_ID"));
                   table.add(R_set.getString("Client_Name"));
                   table.add(R_set.getString("Slot_Given"));
                   table.add(R_set.getString("Start_Date"));
                   table.add(R_set.getString("Duration"));
                   
                }
                
                Deftbl.addRow(table);
                
            }
          
            
        } catch (SQLException ex) {
            Logger.getLogger(CalculateTheBillForStorageJob.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void update_bill()
    {
        int log;
        
         try {
            DBconnector db = new DBconnector();
            Connection con = db.getConnection();
           
            PreparedStatement pre1 = null;
            pre1 = con.prepareStatement("SELECT * FROM `billtable`");
            ResultSet R_set  = pre1.executeQuery();
            
            ResultSetMetaData result = R_set.getMetaData();
            log = result.getColumnCount();
            DefaultTableModel Deftbl = (DefaultTableModel)tableStorageJobINfo3.getModel();
            Deftbl.setRowCount(0);
            
            while(R_set.next())
            {
                Vector table = new Vector();
                for (int i=1; i<=log; i++)
                {
                  
                   table.add(R_set.getString("Bill_Number"));
                   table.add(R_set.getString("Client_id"));
                   table.add(R_set.getString("Duration"));
                   table.add(R_set.getString("Slot"));
                   table.add(R_set.getString("Bill_Amount"));
                   
                }
                
                Deftbl.addRow(table);
                
            }
          
            
        } catch (SQLException ex) {
            Logger.getLogger(CalculateTheBillForStorageJob.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculateTheBillForStorageJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculateTheBillForStorageJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculateTheBillForStorageJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculateTheBillForStorageJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculateTheBillForStorageJob().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCALCBILL;
    private javax.swing.JButton BTNCALCBLANCE;
    private javax.swing.JButton btnCalcBillBacktoMngMenu;
    private javax.swing.JButton btnsavefinal;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tableStorageJobINfo;
    private javax.swing.JTable tableStorageJobINfo1;
    private javax.swing.JTable tableStorageJobINfo2;
    private javax.swing.JTable tableStorageJobINfo3;
    private javax.swing.JTextField txtBillamnt;
    private javax.swing.JTextField txtCID;
    private javax.swing.JTextField txtCName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSID;
    private javax.swing.JTextField txtSJID;
    private javax.swing.JTextField txtbalance;
    private javax.swing.JTextField txtduration;
    private javax.swing.JTextField txtpayed;
    // End of variables declaration//GEN-END:variables
}
