/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.warehousemanagementsystem;

import DBwarehouse.DBconnector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ama
 */
public class CalculateMonthlyReports extends javax.swing.JFrame {

    /**
     * Creates new form CalculateMonthlyReports
     */
    public CalculateMonthlyReports() {
        initComponents();
        
        Updated_Storage_Jobs();
        Update_reg_client();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCalcMonthlyRepbacktoMangMenu = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableClientsMonthlyReport = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableMonthlyreportStorageJobInfo = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("MONTHLY REPORTS");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Warehouse Management System");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(425, 425, 425))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnCalcMonthlyRepbacktoMangMenu.setBackground(new java.awt.Color(0, 153, 153));
        btnCalcMonthlyRepbacktoMangMenu.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnCalcMonthlyRepbacktoMangMenu.setForeground(new java.awt.Color(0, 0, 0));
        btnCalcMonthlyRepbacktoMangMenu.setText("BACK");
        btnCalcMonthlyRepbacktoMangMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcMonthlyRepbacktoMangMenuActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        tableClientsMonthlyReport.setBackground(new java.awt.Color(255, 255, 255));
        tableClientsMonthlyReport.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tableClientsMonthlyReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Client ID", "Client name", "NIC", "Company name", "Address", "Phone number", "Category"
            }
        ));
        tableClientsMonthlyReport.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableClientsMonthlyReport.setRowHeight(25);
        tableClientsMonthlyReport.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tableClientsMonthlyReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableClientsMonthlyReportMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableClientsMonthlyReport);

        tableMonthlyreportStorageJobInfo.setBackground(new java.awt.Color(255, 255, 255));
        tableMonthlyreportStorageJobInfo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tableMonthlyreportStorageJobInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.J.ID", "Client ID", "Client name", "Slot given", "Start date", "Duration"
            }
        ));
        tableMonthlyreportStorageJobInfo.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableMonthlyreportStorageJobInfo.setRowHeight(25);
        tableMonthlyreportStorageJobInfo.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tableMonthlyreportStorageJobInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMonthlyreportStorageJobInfoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableMonthlyreportStorageJobInfo);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Clients Information Table");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Storage Job Information");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCalcMonthlyRepbacktoMangMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(522, 522, 522))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnCalcMonthlyRepbacktoMangMenu)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcMonthlyRepbacktoMangMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcMonthlyRepbacktoMangMenuActionPerformed
        // TODO add your handling code here:
        
        ManagerMenu mngr = new ManagerMenu();
        mngr.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnCalcMonthlyRepbacktoMangMenuActionPerformed

    private void tableClientsMonthlyReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClientsMonthlyReportMouseClicked
        // TODO add your handling code here:

        DefaultTableModel def5 = (DefaultTableModel)tableClientsMonthlyReport.getModel();

        int selectIndex = tableClientsMonthlyReport.getSelectedRow();

//        txtClientID.setText(def5.getValueAt(selectIndex, 0).toString());
//        txtClientName.setText(def5.getValueAt(selectIndex, 1).toString());
//        txtNIC.setText(def5.getValueAt(selectIndex, 2).toString());
//        txtCompanyName.setText(def5.getValueAt(selectIndex, 3).toString());
//        txtAddress.setText(def5.getValueAt(selectIndex, 4).toString());
//        txtPhnNO.setText(def5.getValueAt(selectIndex, 5).toString());
//        cmbCategory.setSelectedItem(def5.getValueAt(selectIndex, 6).toString());
    }//GEN-LAST:event_tableClientsMonthlyReportMouseClicked

    private void tableMonthlyreportStorageJobInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMonthlyreportStorageJobInfoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tableMonthlyreportStorageJobInfoMouseClicked

    public void Updated_Storage_Jobs()
    {
        int log;
        
         try {
            DBconnector db = new DBconnector();
            Connection con = db.getConnection();
           
            PreparedStatement pre1 = null;
            pre1 = con.prepareStatement("SELECT * FROM `addedstoragejobs`");
            ResultSet R_set  = pre1.executeQuery();
            
            ResultSetMetaData result = R_set.getMetaData();
            log = result.getColumnCount();
            DefaultTableModel Deftbl = (DefaultTableModel)tableMonthlyreportStorageJobInfo.getModel();
            Deftbl.setRowCount(0);
            
            while(R_set.next())
            {
                Vector table = new Vector();
                for (int i=1; i<=log; i++)
                {
                  
                   table.add(R_set.getString("Storage_Job_ID"));
                   table.add(R_set.getString("Client_ID"));
                   table.add(R_set.getString("Client_Name"));
                   table.add(R_set.getString("Slot_Given"));
                   table.add(R_set.getString("Start_Date"));
                   table.add(R_set.getString("Duration"));
                   
                }
                
                Deftbl.addRow(table);
                
            }
          
            
        } catch (SQLException ex) {
            Logger.getLogger(CalculateMonthlyReports.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void Update_reg_client()
    {
        int log;
        
         try {
            DBconnector db = new DBconnector();
            Connection con = db.getConnection();
           
            PreparedStatement pre2 = null;
            pre2 = con.prepareStatement("SELECT * FROM `clientsregistration`");
            ResultSet R_set  = pre2.executeQuery();
            
            ResultSetMetaData result = R_set.getMetaData();
            log = result.getColumnCount();
            DefaultTableModel Deftbl = (DefaultTableModel)tableClientsMonthlyReport.getModel();
            Deftbl.setRowCount(0);
            
            while(R_set.next())
            {
                Vector table = new Vector();
                for (int i=1; i<=log; i++)
                {
                   table.add(R_set.getString("Client_ID")); 
                   table.add(R_set.getString("Client_Name"));
                   table.add(R_set.getString("NIC"));
                   table.add(R_set.getString("Company_Name"));
                   table.add(R_set.getString("Address"));
                   table.add(R_set.getString("Phone_Number"));
                   table.add(R_set.getString("Category"));
                }
                
                Deftbl.addRow(table);
                
            }
          
            
        } catch (SQLException ex) {
            Logger.getLogger(CalculateMonthlyReports.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculateMonthlyReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculateMonthlyReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculateMonthlyReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculateMonthlyReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculateMonthlyReports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcMonthlyRepbacktoMangMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableClientsMonthlyReport;
    private javax.swing.JTable tableMonthlyreportStorageJobInfo;
    // End of variables declaration//GEN-END:variables
}
